# Generated by Django 4.2.7 on 2023-11-07 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=90)),
                ('road', models.CharField(max_length=125)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=120)),
                ('accepted', models.BooleanField(default=False)),
                ('fk_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productOrderCompany', to=settings.AUTH_USER_MODEL)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productOrderClient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderIten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('fk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='store.productorder')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItemProduct', to='store.product')),
            ],
        ),
    ]
