# Generated by Django 4.2.7 on 2023-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productorder_fk_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=90)),
                ('road', models.CharField(max_length=125)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderiten',
            name='fk_order',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
