# Generated by Django 4.2.7 on 2023-11-08 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_orderaddress_remove_orderiten_fk_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderiten',
            name='fk_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderAddress', to='store.orderaddress'),
        ),
        migrations.AddField(
            model_name='orderiten',
            name='fk_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productOrderClient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderiten',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
