# Generated by Django 4.2.7 on 2023-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderiten_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderiten',
            name='dt_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
