# Generated by Django 4.2.6 on 2023-10-30 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensage', models.CharField(max_length=255)),
                ('fk_donee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotificationDonee', to=settings.AUTH_USER_MODEL)),
                ('fk_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotificationDonor', to=settings.AUTH_USER_MODEL)),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotificationPet', to='pages.pet')),
            ],
        ),
    ]
