# Generated by Django 4.2.6 on 2023-10-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='telefone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
