# Generated by Django 4.2.4 on 2023-08-23 16:19

import auth_user.managres
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_user.managres.UserManager()),
            ],
        ),
    ]
