# Generated by Django 4.2.4 on 2023-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentrada',
            name='dt_entrada',
            field=models.DateTimeField(),
        ),
    ]
