# Generated by Django 4.2.6 on 2023-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_defaultuser_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
