# Generated by Django 4.2.6 on 2023-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_defaultuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
