# Generated by Django 4.2.6 on 2023-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_alter_defaultuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsaida',
            name='qt_saida',
        ),
        migrations.AlterField(
            model_name='logentrada',
            name='dt_entrada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logsaida',
            name='dt_saida',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
