# Generated by Django 4.2.6 on 2023-10-19 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_user', '0006_remove_logsaida_qt_saida_alter_logentrada_dt_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileImage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
