# Generated by Django 4.2.6 on 2023-10-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_remove_defaultuser_profile_image_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_image',
            new_name='img',
        ),
    ]
