# Generated by Django 4.2.6 on 2023-10-20 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=8)),
                ('desc', models.CharField(max_length=200)),
                ('obs', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_donee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_donee', to=settings.AUTH_USER_MODEL)),
                ('fk_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_donor', to=settings.AUTH_USER_MODEL)),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetsFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petsFound', to='pages.pet')),
            ],
        ),
        migrations.CreateModel(
            name='LostPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lostPets', to='pages.pet')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='imgPet/')),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_pet', to='pages.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_donee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pet')),
            ],
        ),
    ]
