# Generated by Django 4.2.5 on 2023-09-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ImagemPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='media/imgPet')),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_pet', to='pages.pet')),
            ],
        ),
    ]
