# Generated by Django 4.2.6 on 2023-10-13 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_animaisperdidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempet',
            name='imagem',
            field=models.ImageField(default='', upload_to='imgPet/'),
        ),
        migrations.CreateModel(
            name='Requisicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_doador', to=settings.AUTH_USER_MODEL)),
                ('fk_donatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_donatario', to=settings.AUTH_USER_MODEL)),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pet')),
            ],
        ),
    ]
