# Generated by Django 4.2.4 on 2023-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_pet_imagem_imagempet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempet',
            name='imagem',
            field=models.ImageField(upload_to='imgPet/'),
        ),
    ]
