# Generated by Django 4.2.6 on 2023-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_requests_dt_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpets',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PetsFound',
        ),
    ]
