# Generated by Django 4.2.6 on 2023-10-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='fk_doador',
            new_name='fk_donatario',
        ),
    ]
