# Generated by Django 4.2.4 on 2023-11-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_lostpets_found_delete_petsfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requestText',
            field=models.TextField(default='Solicitação de adoção!'),
        ),
    ]
