# Generated by Django 4.2.6 on 2023-10-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_fk_doador_favoritos_fk_donatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimaisEncontrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaisEncontrados', to='pages.pet')),
            ],
        ),
    ]
