# Generated by Django 4.2.7 on 2023-11-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_requests_requesttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='state',
            field=models.CharField(choices=[('REQUESTED', 'requested'), ('DENIED', 'denied'), ('ACCEPTED', 'accepted')], default='REQUESTED', max_length=20),
        ),
    ]
