# Generated by Django 4.2.7 on 2023-11-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fk_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.room'),
        ),
    ]
