# Generated by Django 4.2.7 on 2023-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_fk_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'unread'), ('READ', 'read')], default='UNREAD', max_length=10),
        ),
    ]
